name: Déploiement du rapport Robot Framework

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer Chrome & ChromeDriver
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        LATEST=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/${LATEST}/chromedriver_linux64.zip
        unzip chromedriver.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Installer les dépendances Python
      run: |
        pip install -r requirements.txt

    - name: Lancer les tests
      run: |
        robot -d results tests/

    - name: Publier report.html sur GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./results
        publish_branch: gh-pages
